In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\ahirr\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [9]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [19]:
# Creating arrays
# pass a list to the array to create an array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[0])
print(a)

zero_arr = np.zeros(2)
ones_arr = np.ones(2)
empty_arr = np.empty(2)
step_size = np.arange(0, 10, 2)

print(zero_arr, ones_arr, empty_arr, step_size)

# specifying datatypes in arrays

x = np.ones(2, dtype = np.int64)
print(x)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0.] [1. 1.] [1. 1.] [0 2 4 6 8]
[1 1]


In [24]:
# sorting adding deleting from arrays

arr1 = np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

arr2 = np.array([1,2,3,4,5])

np.concatenate((arr1,arr2))

# to delete just use slicing 

array([2, 1, 5, 3, 7, 4, 6, 8, 1, 2, 3, 4, 5])

In [35]:
# how to know the shape and size of the arrays

array_example = np.array([[1,2,3],[4,5,6],[7,8,9]])

# dimensions
print(array_example.ndim)

# size
print(array_example.size)

# shape 
print(array_example.shape)

# reshaping arrays
np.reshape(array_example, newshape = (1, array_example.size))

# convert 1d arrays to 2d arrays
a = np.array([1,2,3,4,5])
print(a.shape)
a2 = a[np.newaxis, np.newaxis, :]
print(a2.shape)

2
9
(3, 3)
(5,)
(1, 1, 5)
[[[1 2 3 4 5]]]


In [42]:
# indexing and slicing
data = np.array([1,2,3,4,5])
data[1:-1]

array([2, 3, 4])

In [45]:
# selective selection of elements in an array

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
five_down = a[a<5]
five_up = a[a>5]
div_by2 = a[a%2==0]
condition = a[(a>2) & (a < 11)]

In [52]:
# create an array from existing data
a = np.array([1,2,3,4,5,6])
arr1 = a[1:3]
print(arr1)

# vertical stacking
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
print(np.vstack((a1,a2)))

# horizintal stacking
print(np.hstack((a1,a2)))

# reshaping an array
x = np.arange(1,25).reshape(2,12)
print(x)

# deep copy of an array
b2 = a.copy();
print(b2)

[2 3]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[1 2 3 4 5 6]


In [62]:
# basic array operations
data = np.array([1,2])
ones = np.array([3,4])

print(data + ones)
print(data*ones)
print(data - ones)
print(data/ones)

a = np.array([1,2,3,4,5,6,7])
print(np.sum(a))

[4 6]
[3 8]
[-2 -2]
[0.33333333 0.5       ]
28


In [64]:
# Broadcasting
a = np.array([1,2,3,4,5.0])
print(a*1.6)

[1.6 3.2 4.8 6.4 8. ]


In [67]:
# basic functions
print(max(a))
print(min(a))
print(sum(a))

5.0
1.0
15.0


In [72]:
# matrices
mat = np.array([[1,2],[5,6]])
mat.max(axis = 1)

array([2, 6])

In [87]:
# unique items and counts
a = np.array([1,2,3,4,5,6,1,2,3,5,6,7])
unique_val = np.unique(a)
print(unique_val)
unique_val, indices_list, return_count = np.unique(a, return_index=True, return_counts=True)
print(indices_list, return_count, unique_val)

[1 2 3 4 5 6 7]
[ 0  1  2  3  4  5 11] [2 2 2 1 2 2 1] [1 2 3 4 5 6 7]


In [102]:
# transposing and reshaping a matrix
data = np.array([[1,2,3],[4,5,6]])
print(data)
data.reshape((3,2))

print(data.transpose())

# reversing a matrix
a = np.arange(10).reshape(2,5)
print(np.flip(a))
print(np.flip(a, axis = 0))
print(np.flip(a, axis = 1))

a[0] = np.flip(a[0])
print(a)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[9 8 7 6 5]
 [4 3 2 1 0]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
[[4 3 2 1 0]
 [9 8 7 6 5]]
[[4 3 2 1 0]
 [5 6 7 8 9]]


In [105]:
# reshaping and flattening arrays
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
# how to access docstring. very object contains the reference to a string, which is known as the docstring.
# In most cases, this docstring contains a quick and concise summary of the object and how to use it.
print(help(max))
x?

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

None
